# Auto-labeler configuration for pull requests

# Documentation
documentation:
  - '**/*.md'
  - 'docs/**/*'
  - 'README.md'
  - 'TROUBLESHOOTING.md'

# Configuration
config:
  - 'config/**/*'
  - '*.json'
  - '*.toml'
  - '*.yml'
  - '*.yaml'

# Core application
app:
  - 'app/**/*'
  - 'main.py'

# Database
database:
  - 'db/**/*'

# LLM/AI features
llm:
  - 'llm/**/*'

# Utilities
utilities:
  - 'utils/**/*'

# Dependencies
dependencies:
  - 'requirements.txt'
  - 'pyproject.toml'

# Installation/Setup
setup:
  - 'install.*'
  - 'setup.py'

# CI/CD
ci-cd:
  - '.github/**/*'
  - '.github/workflows/**/*'

# Testing
testing:
  - 'tests/**/*'
  - '**/*test*.py'
